example.property: "I AM IN THE DEFAULT"
eureka:
  instance: 
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true 
    service-url:
      defaultZone: http://localhost/8089/eureka
      
    
