example.property: "I AM IN THE DEFAULT"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost/8089/
spring:
  application:
    name: eureka-client
      
    
